const LOADING_CARDS = 'LOADING_CARDS'
const SET_CARDS = 'SET_CARDS'
const LOADING_TYPES = 'LOADING_TYPES'
const SET_TYPES = 'SET_TYPES'

export {
    LOADING_CARDS,
    SET_CARDS,
    LOADING_TYPES,
    SET_TYPES
}